spring:
  application:
    ###服务的名称
    name: springcloud-nacos-base-order
  cloud:
    nacos:
      discovery:
        group: DEFAULT_GROUP
        server-addr: 192.168.1.245:8848

server:
  port: 8093